### ISSUE TITLE
Create a log in page

### ISSUE THREAD

**Issue by andrewbruner** [andrewbruner/weblog#5]
**Is your feature request related to a problem? Please describe.**

I'd like to easily be able to log in from the home page.

**Describe the solution you'd like**

I'd like a simple "log in/log out" button on the home page to redirect the user to the `/authenticate` route.

**Describe alternatives you've considered**

No alternatives have been considered as this is a fairly basic and universal implementaion of user authentication.

**Additional context**

**Comment by andrewbruner** [comment]
**Todos:**

- [ ] Log in button
- [ ] Log out button
- [ ] Welcome message to logged in user

**Comment by andrewbruner** [comment]
Resolved with #9
